### ISSUE TITLE
deployed in k8s, when the pod is rebuilt, the hardware identification will change

### ISSUE THREAD

**Issue by iqihao** [emqx/neuron#1068]
# Issue Template

Please fill in the issue as required.

* System: ubuntu 2204 + k8s 1.21.9 + calico 
* Architecture: amd64
* Version: 2.3.6
* Problem Description: deployed in k8s, when the pod is rebuilt, the hardware identification will change
* Log Information:

硬件识别策略似乎在k8s 下有些问题，使用的源码中提供的chart包。每次pod重建硬件标志会发生变化

**Comment by eeff** [comment]
Literally, `hardware identification` is used to identify a machine uniquely. Neuron's commercial license may be bound to such a `hardware id`, so that Neuron's commercial plugins could use it to ensure that licenses are not abused. 
In k8s environments, checking against license hardware id is doomed to fail since a pod may be scheduled to many different machines. In such cases, you would better apply for a license that is not bound with a hardware id.
